### ISSUE TITLE
current-window-only doesn't harmonize with magit

### ISSUE THREAD

**Issue by holgerschurig** [FrostyX/current-window-only#3]
When I mark a hung and commit it via magit, then the behavior is very weird, as magit deliberately uses several windows. When I press "c" (to commit), then magit normally displays a help buffer in the lower part of the frame. The upper part still displays the various diffs/hunks. The display of the lower window inside the frame is BTW done by transient. So I expect your package not working well with transient, either.

I can now press keys to set options for this commit. Or another "c" to actually commit. And now Magit would normally let me edit the commit message in the upper part of the frame, and the actual diff hunks to be commited in the lower window.

This "two windows with info inside one frame" that happens twice doesn't work well (at all) when current-window-only-mode is on. So Magit behaves quite confusing.

**Comment by FrostyX** [comment]
Hello  @holgerschurig,
thank you for the feedback.

This is strange though, I am using Magit on a daily basis and I didn't have any issues. This is how it looks on my machine:

I stage some changes with `s`

![1](https://github.com/FrostyX/current-window-only/assets/2151771/06d67246-5bfc-46b7-a9d6-875a304d8ec9)

Then I press `c` to commit

![2](https://github.com/FrostyX/current-window-only/assets/2151771/78f2110c-45ca-4f30-ba25-aaa74e3a0379)

I usually don't adjust any parameters and press `c` again. Now a diff appears* and once I make sure it is okay, I can either press `c` or `C-x b` to get to the commit buffer

![3](https://github.com/FrostyX/current-window-only/assets/2151771/734d00e2-8ab0-4f84-a523-1bac131246a8)

Then I can write a commit message and `C-c C-c` to finish.

![4](https://github.com/FrostyX/current-window-only/assets/2151771/c95533ff-a225-4cfd-9909-835202be2baa)



Does it work differently for you? Or maybe the * step is unexpected?

**Comment by velppa** [comment]
Broken magit experience was the reason I stopped using current-window-only, I don’t remember details but is was very annoying. The default window management is tricky and not consistent but with winner-mode we can go back to previous window configuration.

**Comment by FrostyX** [comment]
@velppa I am sorry to hear that. I am using Magit every day and everything works as I would expect. But I am doing only basic things

- Staging files, committing and pushing
- Going through git logs
- Blaming
- Interactively rebasing

If some other use-case is broken, please somebody let me know.
Also if you take a look at the screenshot sequence above and at the git log and showing a commit example here
https://youtu.be/Qut1oO6nqgA?t=171
Does the current-window-only behavior look reasonable to you?

**Comment by velppa** [comment]
I found in my notes why exactly I stopped using current-window-only (nice package, and even better showcase, kudos!).

- In magit during commit I need to q on changes in the index, to write a commit message

**Comment by FrostyX** [comment]
Thank you @grtcdr,
I tried the setting and it does indeed show changes and commit message buffers side by side.

> makes sense as writing an appropriate commit message requires having the ability to visualize one's changes.

I totally agree with this. Personally, I have a comfortable key-bind for `evil-switch-to-windows-last-buffer` so I can easily switch between those two buffers in only one window. And if needed, I jump into some other window and manually open the buffer with changes there.

> Despite being inconsistent with the goals of this package, setting this variable to a non-nil value

For this reason, I don't want to put the `(setq magit-commit-diff-inhibit-same-window t)` setting into the package or have it under some `current-window-only` option.

But maybe we can add some section to the README describing workarounds for unwanted (by some people) cases like this?

**Comment by FrostyX** [comment]
Do you think PR #4 solves this issue?
